### ISSUE TITLE
kinit doesn't seem to be availbale in dbnode{1,2,3}

### ISSUE THREAD

**Issue by niccottrell** [pkdone/MongoSecurityPlaypen#5]
The instructions mentioning requesting a new kerberos key, but can't find kinit in the DB nodes. Any ideas?

**Comment by pkdone** [comment]
In vars/external_vars.yml did you first set "client_auth_method" to "kerberos" (from the default of ldap) before running "vagrant up" for the first time (otherwise kerberos is not used in the VMs)?

**Comment by pkdone** [comment]
Closing due to no response to clarification question.

**Comment by niccottrell** [comment]
That was exactly my problem.
